// Code generated by protoc-gen-go.
// source: params.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	params.proto

It has these top-level messages:
	MailItem
	MailItems
	Back
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MailItem struct {
	ItemId  int32 `protobuf:"varint,1,opt,name=ItemId" json:"ItemId,omitempty"`
	ItemNum int32 `protobuf:"varint,2,opt,name=ItemNum" json:"ItemNum,omitempty"`
}

func (m *MailItem) Reset()                    { *m = MailItem{} }
func (m *MailItem) String() string            { return proto.CompactTextString(m) }
func (*MailItem) ProtoMessage()               {}
func (*MailItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MailItem) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *MailItem) GetItemNum() int32 {
	if m != nil {
		return m.ItemNum
	}
	return 0
}

type MailItems struct {
	MailItems []*MailItem `protobuf:"bytes,1,rep,name=MailItems" json:"MailItems,omitempty"`
}

func (m *MailItems) Reset()                    { *m = MailItems{} }
func (m *MailItems) String() string            { return proto.CompactTextString(m) }
func (*MailItems) ProtoMessage()               {}
func (*MailItems) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MailItems) GetMailItems() []*MailItem {
	if m != nil {
		return m.MailItems
	}
	return nil
}

type Back struct {
	PlayerId  int32      `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	MailItems *MailItems `protobuf:"bytes,2,opt,name=MailItems" json:"MailItems,omitempty"`
}

func (m *Back) Reset()                    { *m = Back{} }
func (m *Back) String() string            { return proto.CompactTextString(m) }
func (*Back) ProtoMessage()               {}
func (*Back) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Back) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Back) GetMailItems() *MailItems {
	if m != nil {
		return m.MailItems
	}
	return nil
}

func init() {
	proto.RegisterType((*MailItem)(nil), "pb.MailItem")
	proto.RegisterType((*MailItems)(nil), "pb.MailItems")
	proto.RegisterType((*Back)(nil), "pb.Back")
}

func init() { proto.RegisterFile("params.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2c, 0x4a,
	0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xb2, 0xe1, 0xe2,
	0xf0, 0x4d, 0xcc, 0xcc, 0xf1, 0x2c, 0x49, 0xcd, 0x15, 0x12, 0xe3, 0x62, 0x03, 0xd1, 0x9e, 0x29,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x50, 0x9e, 0x90, 0x04, 0x17, 0x3b, 0x88, 0xe5, 0x57,
	0x9a, 0x2b, 0xc1, 0x04, 0x96, 0x80, 0x71, 0x95, 0xcc, 0xb9, 0x38, 0x61, 0xba, 0x8b, 0x85, 0xb4,
	0x90, 0x38, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x3c, 0x7a, 0x05, 0x49, 0x7a, 0x30, 0xc1,
	0x20, 0x84, 0xb4, 0x92, 0x3f, 0x17, 0x8b, 0x53, 0x62, 0x72, 0xb6, 0x90, 0x14, 0x17, 0x47, 0x40,
	0x4e, 0x62, 0x65, 0x6a, 0x11, 0xdc, 0x52, 0x38, 0x5f, 0x48, 0x1b, 0xd9, 0x3c, 0x90, 0xc5, 0xdc,
	0x46, 0xbc, 0xc8, 0xe6, 0x15, 0x23, 0x19, 0x98, 0xc4, 0x06, 0xf6, 0x92, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0xa6, 0xa9, 0xa1, 0xf4, 0xe2, 0x00, 0x00, 0x00,
}
