// Code generated by protoc-gen-go.
// source: params.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	params.proto

It has these top-level messages:
	Hero
	Soldier
	ArmyGroup
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hero struct {
	ID       string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	HeroID   int32  `protobuf:"varint,2,opt,name=HeroID" json:"HeroID,omitempty"`
	HeroLv   int32  `protobuf:"varint,3,opt,name=HeroLv" json:"HeroLv,omitempty"`
	HeroStar int32  `protobuf:"varint,4,opt,name=HeroStar" json:"HeroStar,omitempty"`
}

func (m *Hero) Reset()                    { *m = Hero{} }
func (m *Hero) String() string            { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()               {}
func (*Hero) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Hero) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Hero) GetHeroID() int32 {
	if m != nil {
		return m.HeroID
	}
	return 0
}

func (m *Hero) GetHeroLv() int32 {
	if m != nil {
		return m.HeroLv
	}
	return 0
}

func (m *Hero) GetHeroStar() int32 {
	if m != nil {
		return m.HeroStar
	}
	return 0
}

type Soldier struct {
	ID         string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	SoldierId  int32  `protobuf:"varint,2,opt,name=SoldierId" json:"SoldierId,omitempty"`
	SoldierNum int32  `protobuf:"varint,3,opt,name=SoldierNum" json:"SoldierNum,omitempty"`
}

func (m *Soldier) Reset()                    { *m = Soldier{} }
func (m *Soldier) String() string            { return proto.CompactTextString(m) }
func (*Soldier) ProtoMessage()               {}
func (*Soldier) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Soldier) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Soldier) GetSoldierId() int32 {
	if m != nil {
		return m.SoldierId
	}
	return 0
}

func (m *Soldier) GetSoldierNum() int32 {
	if m != nil {
		return m.SoldierNum
	}
	return 0
}

type ArmyGroup struct {
	ID       string     `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Heros    []*Hero    `protobuf:"bytes,2,rep,name=Heros" json:"Heros,omitempty"`
	Soldiers []*Soldier `protobuf:"bytes,3,rep,name=Soldiers" json:"Soldiers,omitempty"`
}

func (m *ArmyGroup) Reset()                    { *m = ArmyGroup{} }
func (m *ArmyGroup) String() string            { return proto.CompactTextString(m) }
func (*ArmyGroup) ProtoMessage()               {}
func (*ArmyGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ArmyGroup) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ArmyGroup) GetHeros() []*Hero {
	if m != nil {
		return m.Heros
	}
	return nil
}

func (m *ArmyGroup) GetSoldiers() []*Soldier {
	if m != nil {
		return m.Soldiers
	}
	return nil
}

func init() {
	proto.RegisterType((*Hero)(nil), "pb.Hero")
	proto.RegisterType((*Soldier)(nil), "pb.Soldier")
	proto.RegisterType((*ArmyGroup)(nil), "pb.ArmyGroup")
}

func init() { proto.RegisterFile("params.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2c, 0x4a,
	0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x4a, 0xe2, 0x62,
	0xf1, 0x48, 0x2d, 0xca, 0x17, 0xe2, 0xe3, 0x62, 0xf2, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x62, 0xf2, 0x74, 0x11, 0x12, 0xe3, 0x62, 0x03, 0x89, 0x7b, 0xba, 0x48, 0x30, 0x29, 0x30,
	0x6a, 0xb0, 0x06, 0x41, 0x79, 0x30, 0x71, 0x9f, 0x32, 0x09, 0x66, 0x84, 0xb8, 0x4f, 0x99, 0x90,
	0x14, 0x17, 0x07, 0x88, 0x15, 0x5c, 0x92, 0x58, 0x24, 0xc1, 0x02, 0x96, 0x81, 0xf3, 0x95, 0xc2,
	0xb9, 0xd8, 0x83, 0xf3, 0x73, 0x52, 0x32, 0x53, 0x8b, 0x30, 0xac, 0x91, 0xe1, 0xe2, 0x84, 0x4a,
	0x79, 0xa6, 0x40, 0x6d, 0x42, 0x08, 0x08, 0xc9, 0x71, 0x71, 0x41, 0x39, 0x7e, 0xa5, 0xb9, 0x50,
	0x0b, 0x91, 0x44, 0x94, 0x52, 0xb8, 0x38, 0x1d, 0x8b, 0x72, 0x2b, 0xdd, 0x8b, 0xf2, 0x4b, 0x0b,
	0x30, 0x8c, 0x96, 0xe3, 0x62, 0x05, 0xb9, 0xa0, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0xdb, 0x88,
	0x43, 0xaf, 0x20, 0x49, 0x0f, 0x24, 0x10, 0x04, 0x11, 0x16, 0x52, 0xe7, 0xe2, 0x80, 0x1a, 0x55,
	0x2c, 0xc1, 0x0c, 0x56, 0xc2, 0x0d, 0x52, 0x02, 0x15, 0x0b, 0x82, 0x4b, 0x26, 0xb1, 0x81, 0x43,
	0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xae, 0xad, 0x54, 0xde, 0x3d, 0x01, 0x00, 0x00,
}
