broker: 'redis://localhost:6379/3'
default_queue: machinery_tasks

result_backend: 'redis://localhost:6379/4'
results_expire_in: 3600

#amqp:
#  binding_key: machinery_tasks
#  exchange: machinery_exchange
#  exchange_type: direct
#  prefetch_count: 3