// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	CalRequest
	MultResult
	DivResult
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CalRequest struct {
	A int32 `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
}

func (m *CalRequest) Reset()                    { *m = CalRequest{} }
func (m *CalRequest) String() string            { return proto.CompactTextString(m) }
func (*CalRequest) ProtoMessage()               {}
func (*CalRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CalRequest) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *CalRequest) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type MultResult struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *MultResult) Reset()                    { *m = MultResult{} }
func (m *MultResult) String() string            { return proto.CompactTextString(m) }
func (*MultResult) ProtoMessage()               {}
func (*MultResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MultResult) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type DivResult struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Mod    int32 `protobuf:"varint,2,opt,name=mod" json:"mod,omitempty"`
}

func (m *DivResult) Reset()                    { *m = DivResult{} }
func (m *DivResult) String() string            { return proto.CompactTextString(m) }
func (*DivResult) ProtoMessage()               {}
func (*DivResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DivResult) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *DivResult) GetMod() int32 {
	if m != nil {
		return m.Mod
	}
	return 0
}

func init() {
	proto.RegisterType((*CalRequest)(nil), "message.CalRequest")
	proto.RegisterType((*MultResult)(nil), "message.MultResult")
	proto.RegisterType((*DivResult)(nil), "message.DivResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Calculator service

type CalculatorClient interface {
	Mult(ctx context.Context, in *CalRequest, opts ...grpc.CallOption) (*MultResult, error)
	Div(ctx context.Context, in *CalRequest, opts ...grpc.CallOption) (*DivResult, error)
}

type calculatorClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorClient(cc *grpc.ClientConn) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Mult(ctx context.Context, in *CalRequest, opts ...grpc.CallOption) (*MultResult, error) {
	out := new(MultResult)
	err := grpc.Invoke(ctx, "/message.Calculator/Mult", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) Div(ctx context.Context, in *CalRequest, opts ...grpc.CallOption) (*DivResult, error) {
	out := new(DivResult)
	err := grpc.Invoke(ctx, "/message.Calculator/Div", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Calculator service

type CalculatorServer interface {
	Mult(context.Context, *CalRequest) (*MultResult, error)
	Div(context.Context, *CalRequest) (*DivResult, error)
}

func RegisterCalculatorServer(s *grpc.Server, srv CalculatorServer) {
	s.RegisterService(&_Calculator_serviceDesc, srv)
}

func _Calculator_Mult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Mult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Calculator/Mult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Mult(ctx, req.(*CalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_Div_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Div(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Calculator/Div",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Div(ctx, req.(*CalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mult",
			Handler:    _Calculator_Mult_Handler,
		},
		{
			MethodName: "Div",
			Handler:    _Calculator_Div_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x34, 0xb8,
	0xb8, 0x9c, 0x13, 0x73, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x78, 0xb8, 0x18, 0x13,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x18, 0x13, 0x41, 0xbc, 0x24, 0x09, 0x26, 0x08, 0x2f,
	0x49, 0x49, 0x85, 0x8b, 0xcb, 0xb7, 0x34, 0xa7, 0x24, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x44, 0x48,
	0x8c, 0x8b, 0xad, 0x08, 0xcc, 0x82, 0x2a, 0x87, 0xf2, 0x94, 0x4c, 0xb9, 0x38, 0x5d, 0x32, 0xcb,
	0xf0, 0x2b, 0x12, 0x12, 0xe0, 0x62, 0xce, 0xcd, 0x4f, 0x81, 0x1a, 0x0d, 0x62, 0x1a, 0x15, 0x81,
	0x9d, 0x91, 0x5c, 0x9a, 0x93, 0x58, 0x92, 0x5f, 0x24, 0x64, 0xc4, 0xc5, 0x02, 0xb2, 0x4a, 0x48,
	0x58, 0x0f, 0xe6, 0x6a, 0x84, 0x1b, 0xa5, 0x10, 0x82, 0x08, 0xe7, 0x28, 0x31, 0x08, 0x19, 0x70,
	0x31, 0xbb, 0x64, 0x96, 0x61, 0xd7, 0x22, 0x04, 0x17, 0x84, 0xbb, 0x4d, 0x89, 0x21, 0x89, 0x0d,
	0x1c, 0x14, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xc2, 0xf8, 0x96, 0x1b, 0x01, 0x00,
	0x00,
}
