// Code generated by protoc-gen-go.
// source: params.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	params.proto

It has these top-level messages:
	MapRes1
	MapRes2
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MapRes1 struct {
	Id    int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Items string `protobuf:"bytes,2,opt,name=items" json:"items,omitempty"`
}

func (m *MapRes1) Reset()                    { *m = MapRes1{} }
func (m *MapRes1) String() string            { return proto.CompactTextString(m) }
func (*MapRes1) ProtoMessage()               {}
func (*MapRes1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MapRes1) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MapRes1) GetItems() string {
	if m != nil {
		return m.Items
	}
	return ""
}

type MapRes2 struct {
	Id    int32           `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Items map[int32]int32 `protobuf:"bytes,2,rep,name=items" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *MapRes2) Reset()                    { *m = MapRes2{} }
func (m *MapRes2) String() string            { return proto.CompactTextString(m) }
func (*MapRes2) ProtoMessage()               {}
func (*MapRes2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MapRes2) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MapRes2) GetItems() map[int32]int32 {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*MapRes1)(nil), "pb.mapRes1")
	proto.RegisterType((*MapRes2)(nil), "pb.mapRes2")
}

func init() { proto.RegisterFile("params.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2c, 0x4a,
	0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xd2, 0xe7, 0x62,
	0xcf, 0x4d, 0x2c, 0x08, 0x4a, 0x2d, 0x36, 0x14, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe1, 0x62, 0xcd, 0x2c, 0x49, 0xcd, 0x2d,
	0x96, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0x1a, 0x19, 0x61, 0x3a, 0x8c, 0x30,
	0x74, 0xe8, 0x20, 0x74, 0x30, 0x6b, 0x70, 0x1b, 0x89, 0xe9, 0x15, 0x24, 0xe9, 0x41, 0xd5, 0xea,
	0x79, 0x82, 0x24, 0x5c, 0xf3, 0x4a, 0x8a, 0x2a, 0xa1, 0x26, 0x49, 0x59, 0x70, 0x71, 0x21, 0x04,
	0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0xa1, 0x86, 0x81, 0x98, 0x20, 0xfb, 0xcb, 0x12, 0x73,
	0x4a, 0x53, 0xc1, 0xf6, 0xb3, 0x06, 0x41, 0x38, 0x56, 0x4c, 0x16, 0x8c, 0x49, 0x6c, 0x60, 0xf7,
	0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xb2, 0x38, 0x03, 0xcf, 0x00, 0x00, 0x00,
}
