// Code generated by protoc-gen-go.
// source: params.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	params.proto

It has these top-level messages:
	Hero
	Item
	Player
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hero struct {
	HeroId   int32 `protobuf:"varint,1,opt,name=HeroId" json:"HeroId,omitempty"`
	HeroLife int32 `protobuf:"varint,2,opt,name=HeroLife" json:"HeroLife,omitempty"`
}

func (m *Hero) Reset()                    { *m = Hero{} }
func (m *Hero) String() string            { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()               {}
func (*Hero) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Hero) GetHeroId() int32 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *Hero) GetHeroLife() int32 {
	if m != nil {
		return m.HeroLife
	}
	return 0
}

type Item struct {
	ItemId  int32 `protobuf:"varint,1,opt,name=ItemId" json:"ItemId,omitempty"`
	ItemNum int32 `protobuf:"varint,2,opt,name=ItemNum" json:"ItemNum,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Item) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *Item) GetItemNum() int32 {
	if m != nil {
		return m.ItemNum
	}
	return 0
}

type Player struct {
	PlayerId   int32   `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	PlayerHero *Hero   `protobuf:"bytes,2,opt,name=PlayerHero" json:"PlayerHero,omitempty"`
	PlayerItem []*Item `protobuf:"bytes,3,rep,name=PlayerItem" json:"PlayerItem,omitempty"`
	PlayerGold int32   `protobuf:"varint,4,opt,name=PlayerGold" json:"PlayerGold,omitempty"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Player) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Player) GetPlayerHero() *Hero {
	if m != nil {
		return m.PlayerHero
	}
	return nil
}

func (m *Player) GetPlayerItem() []*Item {
	if m != nil {
		return m.PlayerItem
	}
	return nil
}

func (m *Player) GetPlayerGold() int32 {
	if m != nil {
		return m.PlayerGold
	}
	return 0
}

func init() {
	proto.RegisterType((*Hero)(nil), "pb.Hero")
	proto.RegisterType((*Item)(nil), "pb.Item")
	proto.RegisterType((*Player)(nil), "pb.Player")
}

func init() { proto.RegisterFile("params.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2c, 0x4a,
	0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xb2, 0xe2, 0x62,
	0xf1, 0x48, 0x2d, 0xca, 0x17, 0x12, 0xe3, 0x62, 0x03, 0xd1, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xac, 0x41, 0x50, 0x9e, 0x90, 0x14, 0x17, 0x07, 0x88, 0xe5, 0x93, 0x99, 0x96, 0x2a, 0xc1,
	0x04, 0x96, 0x81, 0xf3, 0x95, 0x2c, 0xb8, 0x58, 0x3c, 0x4b, 0x52, 0x73, 0x41, 0x7a, 0x41, 0x34,
	0x42, 0x2f, 0x84, 0x27, 0x24, 0xc1, 0xc5, 0x0e, 0x62, 0xf9, 0x95, 0xe6, 0x42, 0xb5, 0xc2, 0xb8,
	0x4a, 0x33, 0x18, 0xb9, 0xd8, 0x02, 0x72, 0x12, 0x2b, 0x53, 0x8b, 0x40, 0x16, 0x40, 0x58, 0x70,
	0xed, 0x70, 0xbe, 0x90, 0x06, 0x17, 0x17, 0x84, 0x0d, 0xb2, 0x12, 0x6c, 0x06, 0xb7, 0x11, 0x87,
	0x5e, 0x41, 0x92, 0x1e, 0x88, 0x1f, 0x84, 0x24, 0x87, 0x50, 0x09, 0xb2, 0x41, 0x82, 0x59, 0x81,
	0x19, 0xa6, 0x12, 0xc4, 0x0f, 0x42, 0x92, 0x13, 0x92, 0x83, 0xa9, 0x74, 0xcf, 0xcf, 0x49, 0x91,
	0x60, 0x01, 0xdb, 0x88, 0x24, 0x92, 0xc4, 0x06, 0x0e, 0x1b, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x9e, 0x87, 0x4b, 0x2a, 0x2b, 0x01, 0x00, 0x00,
}
