// Code generated by protoc-gen-go.
// source: params.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	params.proto

It has these top-level messages:
	ErrorStatus
	Player
	PlayerHero
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorStatus struct {
	Message string                 `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Details []*google_protobuf.Any `protobuf:"bytes,2,rep,name=details" json:"details,omitempty"`
	Params  *google_protobuf.Any   `protobuf:"bytes,3,opt,name=params" json:"params,omitempty"`
}

func (m *ErrorStatus) Reset()                    { *m = ErrorStatus{} }
func (m *ErrorStatus) String() string            { return proto.CompactTextString(m) }
func (*ErrorStatus) ProtoMessage()               {}
func (*ErrorStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ErrorStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorStatus) GetDetails() []*google_protobuf.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *ErrorStatus) GetParams() *google_protobuf.Any {
	if m != nil {
		return m.Params
	}
	return nil
}

type Player struct {
	PlayerId   int32  `protobuf:"varint,1,opt,name=playerId" json:"playerId,omitempty"`
	PlayerName string `protobuf:"bytes,2,opt,name=playerName" json:"playerName,omitempty"`
	PlayerGold int32  `protobuf:"varint,3,opt,name=playerGold" json:"playerGold,omitempty"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Player) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Player) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *Player) GetPlayerGold() int32 {
	if m != nil {
		return m.PlayerGold
	}
	return 0
}

type PlayerHero struct {
	Id       int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	HeroId   int32 `protobuf:"varint,2,opt,name=HeroId" json:"HeroId,omitempty"`
	HeroLv   int32 `protobuf:"varint,3,opt,name=HeroLv" json:"HeroLv,omitempty"`
	HeroLife int32 `protobuf:"varint,4,opt,name=HeroLife" json:"HeroLife,omitempty"`
}

func (m *PlayerHero) Reset()                    { *m = PlayerHero{} }
func (m *PlayerHero) String() string            { return proto.CompactTextString(m) }
func (*PlayerHero) ProtoMessage()               {}
func (*PlayerHero) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PlayerHero) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerHero) GetHeroId() int32 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *PlayerHero) GetHeroLv() int32 {
	if m != nil {
		return m.HeroLv
	}
	return 0
}

func (m *PlayerHero) GetHeroLife() int32 {
	if m != nil {
		return m.HeroLife
	}
	return 0
}

func init() {
	proto.RegisterType((*ErrorStatus)(nil), "pb.ErrorStatus")
	proto.RegisterType((*Player)(nil), "pb.Player")
	proto.RegisterType((*PlayerHero)(nil), "pb.PlayerHero")
}

func init() { proto.RegisterFile("params.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x4f, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x24, 0x5b, 0x93, 0xea, 0xab, 0x78, 0x58, 0x44, 0xd6, 0x1e, 0x24, 0xe4, 0xd4, 0x83, 0x6c,
	0x41, 0xbf, 0xc0, 0x83, 0x68, 0x40, 0x44, 0xd6, 0x2f, 0xd8, 0xb0, 0xaf, 0xb1, 0x90, 0x74, 0xc3,
	0x6e, 0x2a, 0xe4, 0x03, 0xfc, 0x6f, 0xe9, 0xdb, 0xdd, 0xda, 0x8b, 0xb7, 0x99, 0x79, 0xc3, 0xcc,
	0x3c, 0xb8, 0x1c, 0xb4, 0xd3, 0xbd, 0x97, 0x83, 0xb3, 0xa3, 0xe5, 0x6c, 0x68, 0x96, 0xb7, 0xad,
	0xb5, 0x6d, 0x87, 0x6b, 0x52, 0x9a, 0xfd, 0x66, 0xad, 0x77, 0x53, 0x38, 0x57, 0x3f, 0x19, 0x2c,
	0x9e, 0x9d, 0xb3, 0xee, 0x73, 0xd4, 0xe3, 0xde, 0x73, 0x01, 0xf3, 0x1e, 0xbd, 0xd7, 0x2d, 0x8a,
	0xac, 0xcc, 0x56, 0x17, 0x2a, 0x51, 0x2e, 0x61, 0x6e, 0x70, 0xd4, 0xdb, 0xce, 0x0b, 0x56, 0xce,
	0x56, 0x8b, 0x87, 0x6b, 0x19, 0x62, 0x65, 0x8a, 0x95, 0x4f, 0xbb, 0x49, 0x25, 0x13, 0xbf, 0x87,
	0x22, 0x0c, 0x11, 0xb3, 0x32, 0xfb, 0xd7, 0x1e, 0x3d, 0x95, 0x81, 0xe2, 0xa3, 0xd3, 0x13, 0x3a,
	0xbe, 0x84, 0xf3, 0x81, 0x50, 0x6d, 0x68, 0x42, 0xae, 0x8e, 0x9c, 0xdf, 0x01, 0x04, 0xfc, 0xae,
	0x7b, 0x14, 0x8c, 0x06, 0x9e, 0x28, 0x7f, 0xf7, 0x17, 0xdb, 0x19, 0xea, 0xcd, 0xd5, 0x89, 0x52,
	0x7d, 0x01, 0x84, 0x96, 0x57, 0x74, 0x96, 0x5f, 0x01, 0x3b, 0x76, 0xb0, 0xda, 0xf0, 0x1b, 0x28,
	0x0e, 0x7a, 0x6d, 0x28, 0x39, 0x57, 0x91, 0x25, 0xfd, 0xed, 0x3b, 0x26, 0x46, 0x76, 0x58, 0x4a,
	0x68, 0xbb, 0x41, 0x71, 0x16, 0x96, 0x26, 0xde, 0x14, 0xf4, 0xe5, 0xe3, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x05, 0xde, 0x2a, 0x01, 0x8d, 0x01, 0x00, 0x00,
}
