// Code generated by protoc-gen-go.
// source: params.proto
// DO NOT EDIT!

/*
Package params is a generated protocol buffer package.

It is generated from these files:
	params.proto

It has these top-level messages:
	Info
*/
package params

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Info struct {
	Id     int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Scores []int32 `protobuf:"varint,2,rep,packed,name=scores" json:"scores,omitempty"`
	ToId   int32   `protobuf:"varint,3,opt,name=toId" json:"toId,omitempty"`
	FromId int32   `protobuf:"varint,4,opt,name=FromId" json:"FromId,omitempty"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Info) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Info) GetScores() []int32 {
	if m != nil {
		return m.Scores
	}
	return nil
}

func (m *Info) GetToId() int32 {
	if m != nil {
		return m.ToId
	}
	return 0
}

func (m *Info) GetFromId() int32 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func init() {
	proto.RegisterType((*Info)(nil), "Info")
}

func init() { proto.RegisterFile("params.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2c, 0x4a,
	0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x8a, 0xe2, 0x62, 0xf1, 0xcc, 0x4b, 0xcb,
	0x17, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c,
	0x11, 0x12, 0xe3, 0x62, 0x2b, 0x4e, 0xce, 0x2f, 0x4a, 0x2d, 0x96, 0x60, 0x52, 0x60, 0xd6, 0x60,
	0x0d, 0x82, 0xf2, 0x84, 0x84, 0xb8, 0x58, 0x4a, 0xf2, 0x3d, 0x53, 0x24, 0x98, 0xc1, 0x2a, 0xc1,
	0x6c, 0x90, 0x5a, 0xb7, 0xa2, 0xfc, 0x5c, 0xcf, 0x14, 0x09, 0x16, 0xb0, 0x28, 0x94, 0x97, 0xc4,
	0x06, 0xb6, 0xc2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x77, 0x87, 0x5e, 0x6a, 0x72, 0x00, 0x00,
	0x00,
}
